#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"
bspc config presel_feedback_color "#7f849c"

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
dunst &
feh --bg-scale $HOME/Pictures/1322318.jpeg &
polybar &
picom &

sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

xset m 1 1

exec nemo --no-default-window
