#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#313244"
bspc config focused_border_color "#cba6f7"
bspc config presel_feedback_color "#cba6f7"

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
dunst &
feh --bg-scale $HOME/.config/wallpapers/1322318.jpeg &
polybar &
picom &

xset m 1 1

exec nemo --no-default-window
